-- Suppress AUTOPILOT_UPDATE audit noise generated by the optimizer scheduler.
--
-- The "Auto optimize" autopilots run on a cron (as tight as "* * * * *"). Each
-- tick rewrites the whole auto_pilot row via SaveAutoOptimize, changing only
-- bookkeeping columns: execution_status, last_schedule_time, last_executed_time,
-- next_schedule_time. The single audit_auto_pilot_pg trigger (V700) fired on
-- ANY UPDATE with no field filter, so every tick (3+ writes per run) produced a
-- fresh AUTOPILOT_UPDATE audit row -> the admin Audits page was flooded.
--
-- Split the trigger: INSERT/DELETE audit as before; UPDATE audits only when a
-- column OTHER than the four bookkeeping fields changed. Genuine user edits
-- (name, rule, schedule_time, status, notification, attributes, end_at, ...)
-- still produce exactly one audit row; scheduler churn produces none.
-- fn_audit_trigger is unchanged.

DROP TRIGGER IF EXISTS audit_auto_pilot_pg ON auto_pilot;

CREATE TRIGGER audit_auto_pilot_ins_del_pg
    AFTER INSERT OR DELETE ON auto_pilot
    FOR EACH ROW EXECUTE FUNCTION fn_audit_trigger(
        'AUTO_PILOT',
        'AUTOPILOT_CREATE', NULL, 'AUTOPILOT_DELETE'
    );

CREATE TRIGGER audit_auto_pilot_upd_pg
    AFTER UPDATE ON auto_pilot
    FOR EACH ROW
    WHEN (
        (to_jsonb(OLD) - '{execution_status,last_schedule_time,last_executed_time,next_schedule_time}'::text[])
        IS DISTINCT FROM
        (to_jsonb(NEW) - '{execution_status,last_schedule_time,last_executed_time,next_schedule_time}'::text[])
    )
    EXECUTE FUNCTION fn_audit_trigger(
        'AUTO_PILOT',
        NULL, 'AUTOPILOT_UPDATE', NULL
    );
