sonar.projectKey=notification_server

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=squid:S107
sonar.issue.ignore.multicriteria.e1.resourceKey=**/notifications_server/controllers/slack.py
sonar.issue.ignore.multicriteria.e1.lineRegexp=^.*def __getattr__.*$
