sonar.javascript.node.maxspace=4096
sonar.sourceEncoding=UTF-8
sonar.projectKey=nudgebee_nudgebee_AYu-uqjs3aHmDl-AdO6l
sonar.exclusions=src/pages_back/**,src/components1/cloudaccount/**,src/assets/**,src/pages/mock/json/**
