// Atlas project config for nudgebee Postgres migrations. Atlas Community
// edition replaces golang-migrate as the sole engine (PR #33008 / Fixes
// #33007). The cutover happens automatically on first run of the new
// migration Job image — see run-migrations.sh.
//
// Why Atlas
// ---------
// golang-migrate tracked state in a single-row `(version, dirty)` record and
// was strictly forward-only: any file whose timestamp was below the current
// version got SILENTLY skipped on `migrate up`, with no error and no dirty
// flag. That was the V756 / V758 / V760 incident class we kept firefighting
// after every cherry-pick or hotfix cycle. The phantom-version wedge
// (`migrate force <bogus_ts>`) was a similar single-tracker artifact.
//
// Atlas tracks per-file in nudgebee.atlas_schema_revisions. With
// `--exec-order non-linear` (set below), files added later with smaller
// timestamps are detected and applied; the silent-skip class becomes
// structurally impossible. Phantom force is also impossible — atlas has no
// `force` command and revisions are content-addressed by hash.
//
// File-format compat
// ------------------
// Atlas reads our existing `{ts}_V<N>_<name>.up.sql` / `.down.sql` files
// unchanged via `format=golang-migrate`. The only addition is the
// `atlas.sum` checksum file in migrations/app/ (regenerated by
// `atlas migrate hash` whenever migrations are added or modified — handled
// automatically by ./new-migration.sh). No file renames; no schema changes
// to existing migration content.

env "default" {
  // Source of truth for migration files. The `?format=golang-migrate` flag
  // tells Atlas to read our existing .up.sql / .down.sql naming; the down
  // files remain present but Atlas does not auto-apply them on rollback
  // (use `atlas migrate down` explicitly).
  migration {
    dir = "file://migrations/app?format=golang-migrate"

    // Allow files to land out of order. Without this, an EE→test→main
    // promotion that brings ts < current_max would refuse to apply
    // (which is exactly the golang-migrate silent-skip bug, just made loud).
    // With non-linear, Atlas applies the older-ts files in file order and
    // records them in the revisions table. The next promotion is clean.
    //
    // Eyes-open trade-off: Atlas's own docs DISCOURAGE non-linear for general
    // production use because arbitrary out-of-order application "cannot
    // guarantee deterministic behavior and may lead to failures (e.g.,
    // conflicted migrations)". We accept it deliberately: our main→test→prod
    // model with cherry-pick hotfixes makes out-of-order arrivals a DESIGNED,
    // expected condition, not an accident. The "conflicted migrations" risk it
    // warns about is contained by (a) validate_migrations.py — duplicate-ts and
    // V-label reuse are hard-fail collisions; (b) the content-addressed
    // atlas.sum; and (c) the `atlas migrate lint` gate in migrations-validate.yaml
    // (catches nested-tx / destructive changes on new files). What remains
    // unguarded is a genuine data dependency between two out-of-order files
    // (file B assumes file A already ran); keep migrations order-independent.
    exec_order = "non-linear"

    // The atlas_schema_revisions table lives in the same schema as the
    // legacy nudgebee.schema_migrations tracker so it shares lifecycle and
    // backup boundaries with the rest of our migration plumbing.
    revisions_schema = "nudgebee"

    // Lock timeout for atlas's row-based migration lock. 10 minutes is
    // generous for our largest tables (~3M-row index builds were measured at
    // ~2 minutes in V754 dry-runs). If a single migration needs longer than
    // 10 minutes, pass --lock-timeout on the apply CLI in run-migrations.sh.
    // Overlapping migration Jobs (helm retry, manual + cron collision) will
    // fail-fast after the timeout — preferred over blocking the deploy
    // forever.
    lock_timeout = "10m"
  }
}

// Transaction mode is set on the `atlas migrate apply` CLI in
// run-migrations.sh (--tx-mode file). The CLI flag is the documented
// surface; the HCL `tx_mode` attribute is not in atlas's published block
// schema and was a no-op here. Per-file CONCURRENTLY etc. still works via
// the `-- atlas:txmode none` directive at the top of the .up.sql file.
