export const users = [
  { first: "Test", last: "User1", email: "test.user1@nudgebee.com", role: "Admin" },
  { first: "Test", last: "User2", email: "test.user2@nudgebee.com", role: "Admin" },
  { first: "Test", last: "User3", email: "test.user3@nudgebee.com", role: "Admin" },
  { first: "Test", last: "User4", email: "test.user4@nudgebee.com", role: "Admin" },
  { first: "Test", last: "User5", email: "test.user5@gmail.com", role: "Admin" },
  { first: "Test", last: "User6", email: "test.user6@nudgebee.com", role: "Admin" },
  { first: "Test", last: "User7", email: "test.user7@nudgebee.com", role: "Admin" },
  { first: "Test", last: "User8", email: "test.user8@gmail.com", role: "Admin" },
  { first: "Test", last: "User9", email: "test.user9@nudgebee.com", role: "Admin" },
  { first: "Test", last: "User10", email: "test.user10@gmail.com", role: "Admin" },
  { first: "Test", last: "User11", email: "test.user11@nudgebee.com", role: "Admin" },
  { first: "Test", last: "User12", email: "test.user12@nudgebee.com", role: "Admin" },
  { first: "Test", last: "User13", email: "test.user13@nudgebee.com", role: "Admin" },
  { first: "Test", last: "User14", email: "test.user14@nudgebee.com", role: "Admin" },
  { first: "Test", last: "User15", email: "test.user15@gmail.com", role: "Admin" },
  { first: "Test", last: "User16", email: "test.user16@nudgebee.com", role: "Admin" },
  { first: "Test", last: "User17", email: "test.user17@gmail.com", role: "Admin" },
  { first: "Test", last: "User18", email: "test.user18@nudgebee.com", role: "Admin" },
  { first: "Test", last: "User19", email: "test.user19@nudgebee.com", role: "Admin" },
] as const;