/**
 * Weekly event-analysis digests — the b-Cortex "Digests" tab.
 *
 * Wired to backend:
 *   events_list_analysis_digests   history list for the tenant
 *   events_get_analysis_digest     one week, including per-class findings
 *
 * Digests are generated by a scheduled job, so both calls are pure reads —
 * there is no way to trigger generation from the UI.
 */
import { queryGraphQL } from '@lib/HttpService';

/** A class excluded from the review, named so a misjudged exclusion stays visible. */
export interface DigestNoiseClass {
  aggregation_key: string;
  cloud_account_id: string;
  account_name?: string;
  events: number;
  pct: number;
  reason: string;
}

export interface DigestMetrics {
  // Pipeline health
  events_analysed?: number;
  events_complete?: number;
  completion_pct?: number;
  failed_events?: number;
  /** Root-cause stage coverage. Reported apart from completion — rca_analysis runs on a small share of events. */
  rca_events?: number;
  rca_pct?: number;
  // Signal and noise
  real_events?: number;
  synthetic_events?: number;
  suppressed_events?: number;
  noise_pct?: number;
  noise_classes?: DigestNoiseClass[];
  // Recurrence, over real events only
  new_incidents?: number;
  recurrences?: number;
  recurrence_pct?: number;
  // Shape of the week
  failure_classes?: number;
  services?: number;
  p1_pct?: number;
  learnings?: number;
}

export interface DigestClass {
  aggregation_key: string;
  /**
   * The account this class belongs to. Part of its identity, not decoration —
   * the same aggregation key in two accounts is two unrelated incidents with
   * independent recurrence histories.
   */
  cloud_account_id: string;
  account_name: string;
  events: number;
  new_incidents: number;
  recurrences: number;
  worst_recurrence: number;
  services: number;
  priority: string;
  owner?: string;
}

/**
 * The map stage's structured verdict for one failure class.
 *
 * Typed rather than one markdown blob: the UI renders each part as what it is
 * and reads the verdicts directly. Rows written before this shape carry a
 * `finding` string instead and are re-queued by the generator's gap scan.
 */
export interface DigestClassFinding extends DigestClass {
  /** Human name for the class, e.g. "Pod memory exhaustion" for pod_oom_killer_enricher. */
  label: string;
  /** One clause naming the mechanism — read on its own in a collapsed row. */
  headline: string;
  problem: string;
  fix: string;
  blast_radius?: string;
  confidence?: 'high' | 'medium' | 'low';
  cause?: 'change' | 'dependency' | 'code' | 'capacity' | 'security' | 'unknown';
  env?: 'prod' | 'demo' | 'dev' | 'test' | 'lab' | 'unknown';
  /** How many earlier weeks reported this class. Absent or 0 means new this week. */
  carried_over_weeks?: number;
}

export interface DigestPattern {
  title: string;
  stance: 'act now' | 'systemic' | 'harden' | 'fix once' | 'recurring';
  body: string;
}

export interface DigestPlanItem {
  priority: 'P1' | 'P2' | 'P3';
  action: string;
  area: string;
  owner: string;
}

export interface DigestCarryOver {
  aggregation_key: string;
  account_name?: string;
  weeks: number;
}

/**
 * The reduce stage's structured review.
 *
 * `carried_over` and `resolved` are derived from stored digests rather than
 * returned by the model — both claim a pattern is still open or finally fixed,
 * which the data answers exactly.
 */
export interface DigestBriefing {
  snapshot: string[];
  what_broke_lede: string;
  patterns: DigestPattern[];
  plan: DigestPlanItem[];
  hygiene: { noise: string; pipeline: string; confidence: string };
  carried_over: DigestCarryOver[];
  resolved: DigestCarryOver[];
}

export interface Digest {
  id: string;
  tenant_id: string;
  period_start: string;
  period_end: string;
  metrics: DigestMetrics | null;
  top_classes: DigestClass[] | null;
  class_summaries: DigestClassFinding[] | null;
  /** Null on rows generated before the reduce stage returned structure; those rows are re-queued. */
  briefing: DigestBriefing | null;
  summary: string;
  status: 'generated' | 'partial' | 'failed';
  error_message?: string;
  generated_at: string;
}

interface ActionResponse<T> {
  data: T | null;
  errors: unknown[];
}

async function call<T = unknown>(action: string, request: Record<string, unknown>): Promise<ActionResponse<T>> {
  const query = `
    query Digests_${action}($request: ${action}_request!) {
      ${action}(request: $request) {
        data
        errors
      }
    }
  `;
  try {
    const response = await queryGraphQL(query, `Digests_${action}`, { request });
    const root = response?.data?.data?.[action];
    return {
      data: (root?.data as T) ?? null,
      errors: root?.errors ?? response?.data?.errors ?? [],
    };
  } catch (error) {
    return { data: null, errors: [error] };
  }
}

/**
 * The review is tenant-wide, so neither call takes an account — the tenant comes
 * from the session and account attribution lives on each finding.
 */
export const digestsList = (opts?: { limit?: number }) => call<Digest[]>('events_list_analysis_digests', { limit: opts?.limit ?? 52 });

/** periodStart is the week's Monday as YYYY-MM-DD — the digest's storage key. */
export const digestGet = (opts: { periodStart: string }) => call<Digest>('events_get_analysis_digest', { period_start: opts.periodStart });
