/**
 * Weekly event-analysis digests — the b-Cortex "Digests" tab.
 *
 * Wired to backend:
 *   events_list_analysis_digests   history list for one account
 *   events_get_analysis_digest     one week, including per-class findings
 *
 * Digests are generated by a scheduled job, so both calls are pure reads —
 * there is no way to trigger generation from the UI.
 */
import { queryGraphQL } from '@lib/HttpService';

export interface DigestMetrics {
  analyses?: number;
  failed?: number;
  failure_classes?: number;
  events_analysed?: number;
  new_incidents?: number;
  recurring?: number;
  services?: number;
  p1_pct?: number;
  noise_pct?: number;
  learnings?: number;
}

export interface DigestClass {
  aggregation_key: string;
  events: number;
  new_incidents: number;
  worst_recurrence: number;
  services: number;
  priority: string;
  owner?: string;
}

export interface DigestClassFinding extends DigestClass {
  finding: string;
}

export interface Digest {
  id: string;
  tenant_id: string;
  cloud_account_id: string;
  period_start: string;
  period_end: string;
  metrics: DigestMetrics | null;
  top_classes: DigestClass[] | null;
  class_summaries: DigestClassFinding[] | null;
  summary: string;
  status: 'generated' | 'partial' | 'failed';
  error_message?: string;
  generated_at: string;
}

interface ActionResponse<T> {
  data: T | null;
  errors: unknown[];
}

async function call<T = unknown>(action: string, request: Record<string, unknown>): Promise<ActionResponse<T>> {
  const query = `
    query Digests_${action}($request: ${action}_request!) {
      ${action}(request: $request) {
        data
        errors
      }
    }
  `;
  try {
    const response = await queryGraphQL(query, `Digests_${action}`, { request });
    const root = response?.data?.data?.[action];
    return {
      data: (root?.data as T) ?? null,
      errors: root?.errors ?? response?.data?.errors ?? [],
    };
  } catch (error) {
    return { data: null, errors: [error] };
  }
}

export const digestsList = (opts: { accountId: string; limit?: number }) =>
  call<Digest[]>('events_list_analysis_digests', {
    account_id: opts.accountId,
    limit: opts.limit ?? 52,
  });

/** periodStart is the week's Monday as YYYY-MM-DD — the digest's storage key. */
export const digestGet = (opts: { accountId: string; periodStart: string }) =>
  call<Digest>('events_get_analysis_digest', {
    account_id: opts.accountId,
    period_start: opts.periodStart,
  });
