table:
  name: application_group_mapping
  schema: public
object_relationships:
- name: application_group
  using:
    foreign_key_constraint_on: group_id
- name: cloud_account
  using:
    foreign_key_constraint_on: account_id
- name: k8s_workload
  using:
    foreign_key_constraint_on:
    - account_id
    - workload_kind
    - namespace_name
    - workload_name
- name: tenant
  using:
    foreign_key_constraint_on: tenant_id
