{
 "title": "Mongodb Dashboard",
 "description": "MongoDB Dashboard using Mongodb Exporter by percona for MongoDB deployed in Kubernetes (inspired by Opstree dashboard)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(mongodb_up,app_kubernetes_io_instance)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mongodb_up{app_kubernetes_io_instance=\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mongodb Uptime",
   "type": "stat",
   "description": "Mongodb Service Uptime in hours",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_members_uptime{app_kubernetes_io_instance=\"$cluster\", member_state=\"PRIMARY\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "stat",
   "description": "The number of incoming connections from clients to the database server. This number includes the current shell session. Consider the value of connections.available to add more context to this datum.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{app_kubernetes_io_instance=\"$cluster\", conn_type=\"current\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "stat",
   "description": "The number of unused incoming connections available. Consider this value in combination with the value of connections.current to understand the connection load on the database, and the UNIX ulimit Settings document for more information about system thresholds on available connections.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{app_kubernetes_io_instance=\"$cluster\", conn_type=\"available\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "description": "The number of active client connections to the server. Active client connections refers to client connections that currently have operations in progress.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{app_kubernetes_io_instance=\"$cluster\", conn_type=\"available\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Queries",
   "type": "timeseries",
   "description": "The total number of queries received since the mongod instance last started.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{app_kubernetes_io_instance=\"$cluster\", legacy_op_type=\"query\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Allocated Storage to Collections in DB",
   "type": "timeseries",
   "description": "Sum of the space allocated to all collections in the database for document storage, including free space.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mongodb_dbstats_storageSize{app_kubernetes_io_instance=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "{{database}} "
    }
   ]
  },
  {
   "title": "Allocated Storage to Indexs in DB",
   "type": "timeseries",
   "description": "Sum of the space allocated to all indexes in the database, including free index space.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mongodb_dbstats_indexSize{app_kubernetes_io_instance=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Max Member Ping Time - $instance",
   "type": "timeseries",
   "description": "This metric can show a correlation with the replication lag value.",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "mongodb_rs_members_pingMs{app_kubernetes_io_instance=\"$cluster\", instance=\"$instance\"}",
     "legendFormat": "{{member_state}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "description": "MongoDB replication lag occurs when the secondary node cannot replicate data fast enough to keep up with the rate that data is being written to the primary node. It could be caused by something as simple as network latency, packet loss within your network, or a routing issue.",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(mongodb_mongod_replset_oplog_head_timestamp[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "stat",
   "description": "This shows the time since the last election.",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_electionCandidateMetrics_lastElectionDate{app_kubernetes_io_instance=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Cursor totalOpened",
   "type": "timeseries",
   "description": "Number of cursors currently opened by MongoDB for clients",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "mongodb_ss_metrics_cursor_totalOpened{app_kubernetes_io_instance=\"$cluster\"}",
     "legendFormat": "{{instance}} - {{rs_nm}}"
    }
   ]
  }
 ]
}