{
 "title": "PostgreSQL Database",
 "description": "This dashboard works with postgres_exporter for prometheus",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Total Queries Every 5 Minutes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(sum(container_postgres_queries_total{actual_destination_workload_namespace=\"$namespaceName\", actual_destination_workload_name=\"$workloadName\", $destinationIpFilter}[5m]))"
    }
   ]
  },
  {
   "title": "Total Queries by Source in Every 5 Minutes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(src_workload_name) (rate(container_postgres_queries_total{actual_destination_workload_namespace=\"$namespaceName\", actual_destination_workload_name=\"$workloadName\", $destinationIpFilter}[5m]))",
     "legendFormat": "src_workload_name"
    }
   ]
  },
  {
   "title": "Total Query Duration Every 5 Minutes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(sum(container_postgres_queries_duration_seconds_total_sum{actual_destination_workload_namespace=\"$namespaceName\", actual_destination_workload_name=\"$workloadName\", $destinationIpFilter}[5m]))"
    }
   ]
  },
  {
   "title": "Total Query Duration by Source Every 5 Minutes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(src_workload_name) (rate(container_postgres_queries_duration_seconds_total_sum{actual_destination_workload_namespace=\"$namespaceName\", actual_destination_workload_name=\"$workloadName\", $destinationIpFilter}[5m]))",
     "legendFormat": "src_workload_name"
    }
   ]
  }
 ]
}