{
 "title": "NGINX Ingress controller",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Controller Request Volume Every 5 minutes",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{$podNameFilter,controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[5m]))"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",state=\"active\"}[2m]))",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Controller Success Rate (non-4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",status!~\"[4-5].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests{$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Config Reloads Every 5 mins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "avg(irate(nginx_ingress_controller_success{$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "Last Config Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(nginx_ingress_controller_config_last_reload_successful{$podNameFilter,controller_namespace=~\"$namespace\"} == 0)"
    }
   ]
  },
  {
   "title": "Ingress Request Volume Every 5 mins",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(nginx_ingress_controller_requests{$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",exported_namespace=~\"$exported_namespace\",ingress=~\"$ingress\"}[5m])) by (ingress)",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",exported_namespace=~\"$exported_namespace\",ingress=~\"$ingress\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",exported_namespace=~\"$exported_namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Network I/O pressure Every 5 mins",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (irate (nginx_ingress_controller_request_size_sum{$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (irate (nginx_ingress_controller_response_size_sum{$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}) ",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg (rate (nginx_ingress_controller_nginx_process_cpu_seconds_total{$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m])) ",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates Every 5 minute",
   "type": "table",
   "description": "This data is real time, independent of dashboard time range",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\",exported_namespace=~\"$exported_namespace\"}[2m])) by (le, ingress))",
     "legendFormat": "pod"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\",exported_namespace=~\"$exported_namespace\"}[2m])) by (le, ingress))",
     "legendFormat": "pod"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\",exported_namespace=~\"$exported_namespace\"}[2m])) by (le, ingress))",
     "legendFormat": "destination_service"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_sum{ingress!=\"\",$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\",exported_namespace=~\"$exported_namespace\"}[2m])) by (ingress)",
     "legendFormat": "ingress"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_response_size_sum{ingress!=\"\",$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\",exported_namespace=~\"$exported_namespace\"}[2m])) by (ingress)",
     "legendFormat": "ingress"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times (Ingress Namespaces)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\",exported_namespace=~\"$exported_namespace\"}[2m])) by (le))",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\",exported_namespace=~\"$exported_namespace\"}[2m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\",exported_namespace=~\"$exported_namespace\"}[2m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Ingress Request Latency Heatmap (Ingress Namespaces)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",$podNameFilter,controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\",exported_namespace=~\"$exported_namespace\"}[2m])) by (le)",
     "legendFormat": "le"
    }
   ]
  },
  {
   "title": "Ingress Certificate Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds{pod=~\"$workloadName.*\",namespace=~\"$namespace\",class=~\"$controller_class\"}) by (host) - time()",
     "legendFormat": "host"
    }
   ]
  }
 ]
}