{
 "title": "Go Metrics",
 "description": "Golang Application Runtime metrics",
 "tags": [
  "go",
  "golang"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(go_goroutines, namespace)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(go_goroutines{namespace=\"$namespaceName\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory in Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"process.runtime.go.mem.heap_alloc|process_runtime_go_mem_heap_alloc|process_runtime_go_mem_heap_alloc_bytes\", namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "__name__"
    },
    {
     "expr": "{__name__=~\"process.runtime.go.mem.heap_sys|process_runtime_go_mem_heap_sys|process_runtime_go_mem_heap_sys_bytes\", namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "__name__"
    },
    {
     "expr": "{__name__=~\"process.runtime.go.mem.heap_idle|process_runtime_go_mem_heap_idle|process_runtime_go_mem_heap_idle_bytes\", namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "__name__"
    },
    {
     "expr": "{__name__=~\"process.runtime.go.mem.heap_inuse|process_runtime_go_mem_heap_inuse|process_runtime_go_mem_heap_inuse_bytes\", namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "__name__"
    },
    {
     "expr": "{__name__=~\"process.runtime.go.mem.heap_released|process_runtime_go_mem_heap_released|process_runtime_go_mem_heap_released_bytes\", namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "__name__"
    },
    {
     "expr": "sum without(go_memory_type) ({__name__=~\"go.memory.used|go_memory_used|go_memory_used_bytes\", namespace=\"$namespaceName\", $podNameFilter})",
     "legendFormat": "go.memory.used (total)"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"process.runtime.go.mem.heap_inuse|process_runtime_go_mem_heap_inuse|process_runtime_go_mem_heap_inuse_bytes\", namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "__name__"
    },
    {
     "expr": "{__name__=~\"process.runtime.go.mem.heap_sys|process_runtime_go_mem_heap_sys|process_runtime_go_mem_heap_sys_bytes\", namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "__name__"
    },
    {
     "expr": "{__name__=~\"go.memory.used|go_memory_used|go_memory_used_bytes\", go_memory_type=\"stack\", namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "go.memory.used (stack)"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"process.runtime.go.mem.heap_sys|process_runtime_go_mem_heap_sys|process_runtime_go_mem_heap_sys_bytes\", namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "__name__"
    },
    {
     "expr": "sum without(go_memory_type) ({__name__=~\"go.memory.used|go_memory_used|go_memory_used_bytes\", namespace=\"$namespaceName\", $podNameFilter})",
     "legendFormat": "go.memory.used (total)"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"process.runtime.go.mem.live_objects|process_runtime_go_mem_live_objects\", namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "__name__"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "graph",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({__name__=~\"process.runtime.go.mem.heap_objects|process_runtime_go_mem_heap_objects\",namespace=\"$namespaceName\", $podNameFilter}[1m]) or rate({__name__=~\"go.memory.allocations|go_memory_allocations_total\", namespace=\"$namespaceName\", $podNameFilter}[1m])",
     "legendFormat": "__name__"
    }
   ]
  },
  {
   "title": "Memory Used vs Limit",
   "type": "graph",
   "description": "Go runtime memory used (stack + other) vs the soft memory limit (GOMEMLIMIT), from the OTel go.* runtime convention. Replaces the deprecated pointer-lookups metric, which Go always reports as 0.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"go.memory.used|go_memory_used|go_memory_used_bytes\", namespace=\"$namespaceName\", $podNameFilter} or {__name__=~\"go.memory.limit|go_memory_limit_bytes\", namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "__name__"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"process.runtime.go.goroutines|process_runtime_go_goroutines|go.goroutine.count|go_goroutine_count\", namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "__name__"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate({__name__=~\"process.runtime.go.mem.heap_alloc|process_runtime_go_mem_heap_alloc|process_runtime_go_mem_heap_alloc_bytes\", namespace=\"$namespaceName\", $podNameFilter}[1m])",
     "legendFormat": "__name__"
    },
    {
     "expr": "rate({__name__=~\"go.memory.allocated|go_memory_allocated|go_memory_allocated_bytes_total\", namespace=\"$namespaceName\", $podNameFilter}[1m])",
     "legendFormat": "go.memory.allocated (rate)"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"process.runtime.go.gc.pause_total_ns|process_runtime_go_gc_pause_ns_total\", namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "__name__"
    }
   ]
  }
 ]
}