{
 "title": "NodeJS Application Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(nodejs_version_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{namespace=\"$namespaceName\", $podNameFilter}[2m]) * 100",
     "legendFormat": "pod"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{namespace=\"$namespaceName\", $podNameFilter}[2m]) * 100",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{namespace=\"$namespaceName\", $podNameFilter} or nodejs_eventloop_delay_mean{namespace=\"$namespaceName\", $podNameFilter} or nodejs_eventloop_delay_p99{namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(nodejs_version_info{namespace=\"$namespaceName\", $podNameFilter}) by (version)",
     "legendFormat": "version"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{namespace=\"$namespaceName\", $podNameFilter}[1m]))",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "pod"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{namespace=\"$namespaceName\", $podNameFilter} or v8js_memory_heap_limit{namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "pod"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{namespace=\"$namespaceName\", $podNameFilter} or v8js_memory_heap_used{namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "pod"
    },
    {
     "expr": "nodejs_external_memory_bytes{namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "pod"
    },
    {
     "expr": "nodejs_active_requests_total{namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{namespace=\"$namespaceName\", $podNameFilter} or v8js_memory_heap_space_physical_size{namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{namespace=\"$namespaceName\", $podNameFilter} or v8js_memory_heap_used{namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{namespace=\"$namespaceName\", $podNameFilter} or v8js_memory_heap_space_available_size{namespace=\"$namespaceName\", $podNameFilter}",
     "legendFormat": "pod"
    }
   ]
  }
 ]
}