{
 "title": "JVM dashboard",
 "description": "Complete dashboard using metrics from OTEL Exporter",
 "tags": [ "JVM" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "${VAR_JOB}" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(jvm_info{job=\"$job\"},instance)"
   },
   {
    "name": "mempool",
    "query": "label_values(jvm_memory_pool_bytes_max{job=\"$job\", namespace=\"$namespaceName\", $podNameFilter}, pool)"
   },
   {
    "name": "memarea",
    "query": "label_values(jvm_memory_bytes_used{job=\"$job\", namespace=\"$namespaceName\", $podNameFilter}, area)"
   }
  ]
 },
 "panels": [
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"process.runtime.jvm.memory.usage|process_runtime_jvm_memory_usage|process_runtime_jvm_memory_usage_bytes|jvm.memory.used|jvm_memory_used|jvm_memory_used_bytes\",namespace=\"$namespaceName\", $podNameFilter})",
     "legendFormat": "pod"
    },
    {
     "expr": "avg({__name__=~\"process.runtime.jvm.memory.limit|process_runtime_jvm_memory_limit|process_runtime_jvm_memory_limit_bytes|jvm.memory.limit|jvm_memory_limit|jvm_memory_limit_bytes\",namespace=\"$namespaceName\", $podNameFilter})",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"process.runtime.jvm.classes.loaded|process_runtime_jvm_classes_loaded_total|jvm.class.count|jvm_class_count\", namespace=\"$namespaceName\", $podNameFilter})",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"process.runtime.jvm.gc.duration_sum|process_runtime_jvm_gc_duration_seconds_sum|jvm.gc.duration_sum|jvm_gc_duration_sum\", namespace=\"$namespaceName\", $podNameFilter})",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"process.runtime.jvm.gc.duration_count|process_runtime_jvm_gc_duration_seconds_count|jvm.gc.duration_count|jvm_gc_duration_count\",namespace=\"$namespaceName\", $podNameFilter})",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"process.runtime.jvm.threads.count|process_runtime_jvm_threads_count|jvm.thread.count|jvm_thread_count\",namespace=\"$namespaceName\", $podNameFilter})",
     "legendFormat": "pod"
    },
    {
     "expr": "avg({__name__=~\"process.runtime.jvm.threads.count|process_runtime_jvm_threads_count\", daemon=\"true\", namespace=\"$namespaceName\", $podNameFilter} or {__name__=~\"jvm.thread.count|jvm_thread_count\", jvm_thread_daemon=\"true\", namespace=\"$namespaceName\", $podNameFilter})",
     "legendFormat": "pod"
    }
   ]
  }
 ]
}