{
 "title": "RabbitMQ Monitoring",
 "description": "Rabbitmq stats and alerting using RabbitMQ Exporter (https://github.com/kbudde/rabbitmq_exporter)",
 "tags": [
  "rabbitmq",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(rabbitmq_running, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Connections, channels and consumers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_connections{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"})",
     "legendFormat": "connections"
    },
    {
     "expr": "sum(rabbitmq_channels{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"})",
     "legendFormat": "channels"
    },
    {
     "expr": "sum(rabbitmq_queue_consumers{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"})",
     "legendFormat": "consumers"
    }
   ]
  },
  {
   "title": "Messages status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"})",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(rabbitmq_queue_messages_published_total{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"})",
     "legendFormat": "published"
    },
    {
     "expr": "sum(rabbitmq_queue_messages_unacked{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"})",
     "legendFormat": "unacked"
    }
   ]
  },
  {
   "title": "Total Messages On Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"})"
    }
   ]
  },
  {
   "title": "Disk Free vs Used (MB)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_disk_space_available_bytes{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}/(1024*1024))",
     "legendFormat": "free"
    },
    {
     "expr": "sum(rabbitmq_disk_space_available_limit_bytes{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}/(1024*1024))",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}