{
 "title": "JVM dashboard",
 "description": "Complete dashboard using NB Node Agents",
 "tags": [ "JVM" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "${VAR_JOB}" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(jvm_info{job=\"$job\"},instance)"
   },
   {
    "name": "mempool",
    "query": "label_values(jvm_memory_pool_bytes_max{job=\"$job\", namespace=\"$namespaceName\", $podNameFilter}, pool)"
   },
   {
    "name": "memarea",
    "query": "label_values(jvm_memory_bytes_used{job=\"$job\", namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}, area)"
   }
  ]
 },
 "panels": [
  {
   "title": "JVM Heap Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=\"container_jvm_heap_size_bytes\", $sourceContainerFilter}/(1024*1024))",
     "legendFormat": "pod"
    },
    {
     "expr": "avg({__name__=\"container_jvm_heap_used_bytes\", $sourceContainerFilter}/(1024*1024))",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=\"container_jvm_gc_time_seconds\", $sourceContainerFilter})",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "JVM Safepoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=\"container_jvm_safepoint_sync_time_seconds\", $sourceContainerFilter})",
     "legendFormat": "pod"
    },
    {
     "expr": "avg({__name__=\"container_jvm_safepoint_time_seconds\", $sourceContainerFilter})",
     "legendFormat": "pod"
    }
   ]
  }
 ]
}