{
 "title": "Python dashboard",
 "description": "Complete dashboard using metrics from OTEL Exporter",
 "tags": [ "Cpython" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "${VAR_JOB}" }
  ]
 },
 "panels": [
  {
   "title": "Python Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"process.runtime.cpython.memory|process_runtime_cpython_memory_bytes\", type=\"rss\", namespace=\"$namespaceName\", $podNameFilter}/(1024*1024))",
     "legendFormat": "pod"
    },
    {
     "expr": "avg({__name__=~\"process.runtime.cpython.memory|process_runtime_cpython_memory_bytes\", type=\"vms\", namespace=\"$namespaceName\", $podNameFilter}/(1024*1024))",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "Python CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"process.runtime.cpython.cpu_time|process_runtime_cpython_cpu_time_seconds_total\", type=\"system\", namespace=\"$namespaceName\", $podNameFilter}/(1024*1024))",
     "legendFormat": "pod"
    },
    {
     "expr": "avg({__name__=~\"process.runtime.cpython.cpu_time|process_runtime_cpython_cpu_time_seconds_total\", type=\"user\", namespace=\"$namespaceName\", $podNameFilter}/(1024*1024))",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"process.runtime.cpython.gc_count|process_runtime_cpython_gc_count_bytes_total\",namespace=\"$namespaceName\", $podNameFilter})",
     "legendFormat": "pod"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg({__name__=~\"process.runtime.cpython.thread_count|process_runtime_cpython_thread_count\",namespace=\"$namespaceName\", $podNameFilter})",
     "legendFormat": "pod"
    }
   ]
  }
 ]
}