{
 "title": "Redis Dashboard",
 "description": "Redis Dashboard for Prometheus Redis Exporter 1.x, it works with helm stable/redis-ha exporter.\r\n\r\nIf you missing redis memory utilization, please modify \"maxmemory\" value in values.yaml",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(redis_up, namespace)"
   },
   {
    "name": "pod_name",
    "label": "Pod Name",
    "query": "label_values(redis_up{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "instance",
    "query": "label_values(redis_up{namespace=\"$namespace\", pod=\"$pod_name\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}[1m])"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage (MB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"} / (1024*1024) ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"} / (1024*1024) ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}[5m])",
     "legendFormat": "input"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}[5m])",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}) by (db)",
     "legendFormat": "db"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}) - sum (redis_db_keys_expiring{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}[5m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}[5m])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"} [1m]))",
     "legendFormat": "cmd"
    }
   ]
  },
  {
   "title": "Redis connected clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{namespace=\"$namespaceName\", pod=~ \"$workloadName.*\"}"
    }
   ]
  }
 ]
}